// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

const manifest = {
  sections: {},
  site: "@kiwi-app/kiwi-nextjs",
};

export default manifest;
