// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

const manifest = {
  sections: {},
  loaders: {},
  baseUrl: import.meta.url,
};

export default manifest;
