const {
  prettyProtectedFileContent,
  packageName,
  prettyFileContent,
} = require('../infrastructure/commons');

const pageTemplate = prettyProtectedFileContent(`
    import options from '@kiwi-options';
    import { CatchAll } from '${packageName}';
    import ClientComponent from './client';
    import ServerComponent from './server';
    
    const Page = CatchAll(options, ClientComponent, ServerComponent);

    export default Page;    
`);

const clientCodeTemplate = prettyProtectedFileContent(
  `
    import options from '@kiwi-options';
    import { CatchAllClient } from '${packageName}';
    
    const Page = CatchAllClient(options);

    export default Page;  
`,
  '"use client"',
);

const serverCodeTemplate = prettyProtectedFileContent(`
    import { CatchAllServer } from '${packageName}';
    export default CatchAllServer;    
`);

const routeTemplate = prettyProtectedFileContent(`
    import options from '@kiwi-options';
    import { LiveRoute } from '${packageName}';

    export const { GET, POST, OPTIONS, PATCH } = LiveRoute(options);
`);

const optionsTemplate = prettyFileContent(`
    // DO NOT REMOVE. This file is generated by Kiwi.
    // This file SHOULD be checked into source version control.

    import manifest from '@manifest';
    import { KiwiOptions } from '${packageName}';

    const options: KiwiOptions = {
      manifest,
    };

    export default options;
`);

module.exports = {
  pageTemplate,
  clientCodeTemplate,
  serverCodeTemplate,
  optionsTemplate,
  routeTemplate,
};
