const root = require('path').resolve();
const prettier = require('prettier');
const packageJson = require(`${root}/package.json`);

const userKiwiConfig = packageJson.KiwiConfig || {};
const defaultKiwiConfig = {
    moduleFileNameCase: 'kebab',
    ...userKiwiConfig,
};

async function prettyFileContent(content) {
    const formattedOutput = await prettier.format(content, {
        parser: "babel-ts",
    });

    return formattedOutput;
}

async function prettyProtectedFileContent(content) {
  const template = `
        // DO NOT EDIT. This file is generated by Kiwi.
        // This file SHOULD be checked into source version control.

        ${content}
    `;
    const formattedOutput = prettyFileContent(template);
    return formattedOutput;
}

function getKiwiConfig(key) {
    if (!Object.hasOwn(defaultKiwiConfig, key))
        return null;

    const config = defaultKiwiConfig[key];
    return config;
}

module.exports = {
    prettyFileContent,
    prettyProtectedFileContent,
    getKiwiConfig,
};
