// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import { KiwiManifest } from '.';

const manifest: KiwiManifest = {
  sections: {},
  site: '@kiwi-app/nextjs',
};

export default manifest;
